/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Quotes;



import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.String;
import java.util.ArrayList;


public class App {
    public String getGreeting() {

        return "Hello World!";
    }
   //I got this Idea from the internet(stack overflow) 
    public static void main(String[] args) {

       try{
           FileReader jsonFiles =new FileReader("recentquotes.json");

           ArrayList<Quote> q=readJsonFile(jsonFiles);

           int rand =(int)(Math.random() * (q.size()));

           System.out.println(q.get(rand).toString());


       } catch (FileNotFoundException e) {
           e.printStackTrace();
       }


    }
    public static ArrayList<Quote> readJsonFile(FileReader jsonFiles){
        Gson g =new  Gson();

        BufferedReader reader= new BufferedReader(jsonFiles);

        ArrayList<Quote> q= g.fromJson(reader,new TypeToken<ArrayList<Quote>>() {}.getType());

        try{
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
       return q;
    }

}



